include: package:pedantic/analysis_options.yaml

linter:
  rules:
    # Style rules
    - camel_case_types
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    #- lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments
    # Usage rules
    - prefer_interpolation_to_compose_strings
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - prefer_expression_function_bodies
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - empty_statements
    - unnecessary_new
    - unnecessary_this
    - unnecessary_const
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_lambdas
    - unnecessary_getters_setters
    #Design rules
    - avoid_setters_without_getters
    - avoid_returning_null
    - avoid_return_types_on_setters

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    missing_required_param: warning
    parameter_assignments: warning
    missing_return: error
    todo: ignore
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else