// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAJC5stWHXN54QFlrCyqHPzLt8iIC4GqY',
    appId: '1:553589881293:web:6cc1b6c865fde701c72c84',
    messagingSenderId: '553589881293',
    projectId: 'flutterfire-ui',
    authDomain: 'flutterfire-ui-390d4.firebaseapp.com',
    storageBucket: 'flutterfire-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKuBn-4ynPsA-qMcC_hHo55Beq0d35GNw',
    appId: '1:553589881293:android:cb04c526bedc48c4c72c84',
    messagingSenderId: '553589881293',
    projectId: 'flutterfire-ui',
    storageBucket: 'flutterfire-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLE2-OJJaHjhj1cUE1dZZZ_PPZV4LIiqk',
    appId: '1:553589881293:ios:f683ff7cc4305e0dc72c84',
    messagingSenderId: '553589881293',
    projectId: 'flutterfire-ui',
    storageBucket: 'flutterfire-ui.appspot.com',
    iosClientId: '553589881293-1kgeh3otfae1nqd92i9m3mr0ecqhs8vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLE2-OJJaHjhj1cUE1dZZZ_PPZV4LIiqk',
    appId: '1:553589881293:ios:f683ff7cc4305e0dc72c84',
    messagingSenderId: '553589881293',
    projectId: 'flutterfire-ui',
    storageBucket: 'flutterfire-ui.appspot.com',
    iosClientId: '553589881293-1kgeh3otfae1nqd92i9m3mr0ecqhs8vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterui',
  );
}
